name: flysystem-cache-adapter

services:

  php:
    container_name: php
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        PHP_VERSION: "${PHP_VERSION}"
    env_file:
      - .env
    volumes:
      - .:/app
    command: [ "tail", "-f", "/dev/null" ]
